// Write-time near-duplicate detection (plan 013 WP4). `findNearDuplicates` is a pure
// cosine-over-weighted-tokens policy (title ×3, tags ×2, body ×1) enforced at the CLI
// edges (kb:add, kb:curate --supersede), never inside the store.
//
// These fixtures are FROZEN COPIES of real live entries (verbatim title/tags/body as of
// plan 013 WP4). They are copied in — the tests deliberately never read the live
// knowledge/ dir, so a future `--force`d or hand-authored similar pair can never redden
// CI. Cosine is pairwise-independent (unlike searchEntries' pool-relative IDF), so a
// pair's score here equals its score in the full 16-entry corpus.

import { test, expect } from "bun:test";
import { findNearDuplicates, DUP_THRESHOLD } from "../src/index";
import type { KnowledgeEntry } from "../src/index";

function mk(partial: Partial<KnowledgeEntry> & { id: string; title: string; body: string }): KnowledgeEntry {
  return { type: "lesson", tags: [], created: "2026-06-26", ...partial };
}

// --- Frozen fixtures: 6 real entries spanning distinct topics. The judge-vocabulary
// pair (trigger-surface × judge-pool) is the tightest legitimate pair in the live corpus
// (~0.47), included on purpose to pin the shipped threshold against the real worst case.

const INDEX_ARTIFACT = mk({
  id: "index-is-a-build-artifact",
  type: "decision",
  title: "knowledge/INDEX.md is generated and byte-match gated, never hand-edited",
  tags: ["knowledge-base", "gate"],
  body:
    "`knowledge/INDEX.md` is generated by `bun run kb:index` from\n" +
    "`knowledge/entries/*.md`. Never hand-edit it — it is a build artifact, exactly\n" +
    "like `.claude-plugin/marketplace.json`.\n\n" +
    "`bun run kb:check` (part of `bun run check`) asserts the committed INDEX.md\n" +
    "byte-matches a fresh render and stays within the 200-line / 25KB budget. A\n" +
    "forgotten `kb:index` or a hand-edit fails the gate. Budget overflow is the\n" +
    "deliberate curate/prune signal — the KB's rot mechanism (the index split alone\n" +
    "does not prevent rot).\n",
});

const STORAGE_PORT = mk({
  id: "storage-is-a-port",
  type: "pattern",
  title: "Storage is a port, not a choice — files first, DB/MCP as later adapters",
  tags: ["architecture", "ports", "knowledge-base"],
  body:
    "ObjectCore treats storage as a PORT, then swaps adapters at a trigger — never a\n" +
    "rewrite. The catalog proved it: `CatalogSource` (Git files → Turso at Stage 3)\n" +
    "feeds the pure `deriveCatalog`, served at the frozen `/v1/marketplace.json` seam.\n\n" +
    "The knowledge base copies the discipline: `KnowledgeStore` is the port;\n" +
    "`FileKnowledgeStore` is operated now (git-tracked, diffable in PRs so every\n" +
    "written lesson is reviewable). A `DbKnowledgeStore` (Turso, reusing\n" +
    "`@objectcore/registry-db`) lights up at the same kind of trigger Stage 3 had. An\n" +
    "MCP resource server is a later ACCESS seam *over* a store (the KB's equivalent of\n" +
    "the HTTP route), not a storage backend. Build files-first behind the port so\n" +
    "DB/MCP are relocations, not rewrites.\n",
});

const JUDGE_POOL = mk({
  id: "judge-pool-distractor",
  type: "gotcha",
  title: "Adding a catalog surface can flip another plugin's borderline judge routing",
  tags: ["evals", "judge", "delegation", "activation", "trigger-surface"],
  body:
    "The activation/delegation judge (AnthropicJudge) runs at temperature 0 and routes each " +
    "prompt against the WHOLE catalog's surface pool (all skills for activation, all agents for " +
    "delegation). So adding a new plugin's skill/agent changes the candidate set for EVERY " +
    "existing case and can flip a borderline-but-passing case belonging to an UNRELATED plugin: " +
    "a new same-flavored surface acts as a distractor, and Haiku's 'when in doubt, fire nothing' " +
    "bias returns null — the verdict's reason may even affirm the correct match while the label " +
    "disagrees. Because temperature is 0 the result is deterministic, so re-running the gate does " +
    "NOT fix it. Fix by DISJOINING the descriptions.\n",
});

const SUBAGENT_TOOLS = mk({
  id: "subagent-tools-comma-serialization",
  type: "gotcha",
  title: "Serialize subagent tools as comma-separated strings, not YAML arrays",
  tags: ["subagents", "forge", "gotcha"],
  body:
    "In a plugin agent's frontmatter, `tools` / `disallowedTools` / `skills` accept\n" +
    "either a YAML array (`tools: [Read, Bash]`) or a comma-separated string\n" +
    "(`tools: Read, Bash`), but the ARRAY form has a known spawn-time bug that can\n" +
    "silently drop the first/last item. The forge engine (`scaffold.ts` `agentDoc`)\n" +
    "emits the comma-separated form.\n",
});

const RELEASE_MERGE = mk({
  id: "release-auto-publishes-on-merge",
  type: "lesson",
  title: "Merging to main auto-publishes current versions; changesets only bump",
  tags: ["release", "ci", "stage-2"],
  body:
    "Merging to `main` runs the release workflow, which tags each plugin\n" +
    "`{plugin}--v{semver}` at its CURRENT version (idempotent), SHA-pins the catalog,\n" +
    "attests it, and runs `registry:ingest` into Turso. So a plugin's FIRST publish\n" +
    "needs no changeset — after a feature merge it is already live and SHA-pinned.\n",
});

const TRIGGER_SURFACE = mk({
  id: "a-trigger-surface-is-gated-whether-it-s-a-skill-or-an-agent-same-coverage-readiness-judge-path",
  type: "pattern",
  title: "A trigger surface is gated whether it's a skill or an agent — same coverage/readiness/judge path",
  tags: ["evals", "agents", "delegation", "gate", "eddops"],
  body:
    "An agent's `description` decides when the orchestrator delegates to it — the same kind of " +
    "trigger surface a skill's description is for activation — so it must be gated the same way, " +
    "never enter the catalog ungated. The shape mirrors skill activation exactly: a per-plugin " +
    "`evals/delegation.json` (positive + negative cases), a deterministic coverage check (every " +
    "agent needs a positive case), a readiness check (a negative case + no stub body), and the " +
    "SAME `Judge` routing a prompt against the agent-surface pool. forge refuses an agent with no " +
    "positive delegation case, just as it refuses a skill with no activation case.\n",
});

const FIXTURES: KnowledgeEntry[] = [
  INDEX_ARTIFACT,
  STORAGE_PORT,
  JUDGE_POOL,
  SUBAGENT_TOOLS,
  RELEASE_MERGE,
  TRIGGER_SURFACE,
];

/** A candidate view (title/tags/body) of an entry — what the CLIs pass. */
function asCandidate(e: KnowledgeEntry): { title: string; tags?: string[]; body: string } {
  return { title: e.title, tags: e.tags, body: e.body };
}

// --- identical → ~1.0 and trips ---------------------------------------------------

test("an identical candidate scores ~1.0 and trips the threshold", () => {
  const hits = findNearDuplicates(asCandidate(INDEX_ARTIFACT), FIXTURES);
  expect(hits.length).toBeGreaterThan(0);
  expect(hits[0]!.id).toBe("index-is-a-build-artifact");
  expect(hits[0]!.score).toBeCloseTo(1, 6);
  expect(hits[0]!.score).toBeGreaterThanOrEqual(DUP_THRESHOLD);
  expect(hits[0]!.title).toBe(INDEX_ARTIFACT.title);
});

// --- a paraphrase (same facts, reworded) still trips ------------------------------

test("a reworded copy of a real entry still trips the threshold", () => {
  const paraphrase = {
    title: "Never hand-edit the generated INDEX file",
    tags: ["knowledge-base", "gate"],
    body:
      "The knowledge base INDEX.md is a build artifact produced by kb:index, just like " +
      "marketplace.json. Editing it by hand fails the byte-match check in kb:check. " +
      "Regenerate it with kb:index instead of touching it directly; budget overflow is the " +
      "curate/prune signal.",
  };
  const hits = findNearDuplicates(paraphrase, FIXTURES);
  const match = hits.find((h) => h.id === "index-is-a-build-artifact");
  expect(match).toBeDefined();
  expect(match!.score).toBeGreaterThanOrEqual(DUP_THRESHOLD);
});

// --- distinct fixtures are all pairwise below the shipped threshold (the pin) ------

test("every distinct fixture pair scores below the shipped DUP_THRESHOLD", () => {
  let max = 0;
  let maxPair = "";
  for (let i = 0; i < FIXTURES.length; i++) {
    for (let j = 0; j < FIXTURES.length; j++) {
      if (i === j) continue;
      const a = FIXTURES[i]!;
      const b = FIXTURES[j]!;
      // threshold 0 → the raw pairwise score regardless of the cutoff.
      const [m] = findNearDuplicates(asCandidate(a), [b], { threshold: 0 });
      const score = m?.score ?? 0;
      expect(score).toBeLessThan(DUP_THRESHOLD);
      if (score > max) {
        max = score;
        maxPair = `${a.id} × ${b.id}`;
      }
    }
  }
  // The tightest legitimate pair is the two judge-vocabulary entries (~0.47) — the
  // calibrated worst case. It must remain safely under the shipped threshold.
  expect(max).toBeGreaterThan(0.4);
  expect(max).toBeLessThan(DUP_THRESHOLD);
  expect(maxPair).toContain("judge-pool-distractor");
});

// --- excludeIds excludes -----------------------------------------------------------

test("excludeIds drops the named entry from the comparison", () => {
  const cand = asCandidate(INDEX_ARTIFACT);
  const withIt = findNearDuplicates(cand, FIXTURES);
  expect(withIt.map((h) => h.id)).toContain("index-is-a-build-artifact");

  const without = findNearDuplicates(cand, FIXTURES, {
    excludeIds: ["index-is-a-build-artifact"],
  });
  expect(without.map((h) => h.id)).not.toContain("index-is-a-build-artifact");
  // Nothing else near-duplicates the index entry, so excluding it leaves no matches.
  expect(without).toEqual([]);
});

// --- zero-vector / empty candidate → no matches, no NaN ---------------------------

test("an empty or all-stopword candidate yields no matches and never NaN", () => {
  expect(findNearDuplicates({ title: "", body: "" }, FIXTURES)).toEqual([]);
  // Every token here is a stopword or a length-1 residue → empty vector.
  expect(findNearDuplicates({ title: "the a an is to of", body: "" }, FIXTURES)).toEqual([]);

  // A real candidate: every pairwise score is a finite number in [0,1], never NaN.
  const scored = findNearDuplicates(asCandidate(STORAGE_PORT), FIXTURES, { threshold: 0 });
  expect(scored.length).toBe(FIXTURES.length); // scores everything at threshold 0
  for (const m of scored) {
    expect(Number.isNaN(m.score)).toBe(false);
    expect(m.score).toBeGreaterThanOrEqual(0);
    expect(m.score).toBeLessThanOrEqual(1);
  }
});

// --- opts.threshold override respected ---------------------------------------------

test("opts.threshold overrides the default cutoff in both directions", () => {
  // The judge-vocabulary pair (~0.47) is below the default 0.57 → no match by default…
  const byDefault = findNearDuplicates(asCandidate(JUDGE_POOL), [TRIGGER_SURFACE]);
  expect(byDefault).toEqual([]);
  // …but a lower threshold surfaces it.
  const lowered = findNearDuplicates(asCandidate(JUDGE_POOL), [TRIGGER_SURFACE], {
    threshold: 0.4,
  });
  expect(lowered.map((h) => h.id)).toEqual([
    "a-trigger-surface-is-gated-whether-it-s-a-skill-or-an-agent-same-coverage-readiness-judge-path",
  ]);
  // A threshold above 1 suppresses even an identical candidate.
  const impossible = findNearDuplicates(asCandidate(INDEX_ARTIFACT), FIXTURES, {
    threshold: 1.01,
  });
  expect(impossible).toEqual([]);
});

// --- filter-agnostic: archived entries in the list are still compared -------------

test("findNearDuplicates compares whatever entries it is handed (status-agnostic)", () => {
  // The FILTERING (active-only) is the caller's job — this function does not look at
  // status. An archived copy passed in the list is still scored + returned.
  const archived: KnowledgeEntry = {
    ...INDEX_ARTIFACT,
    id: "index-is-a-build-artifact-archived",
    status: "superseded",
    supersededBy: "some-replacement",
  };
  const hits = findNearDuplicates(asCandidate(INDEX_ARTIFACT), [archived]);
  expect(hits.map((h) => h.id)).toEqual(["index-is-a-build-artifact-archived"]);
  expect(hits[0]!.score).toBeCloseTo(1, 6);
});

// --- deterministic sort: score DESC then id ASC ------------------------------------

test("matches sort by score desc then id asc (deterministic tie-break)", () => {
  // Two entries with identical content but different ids → identical scores → id-asc.
  const zzz: KnowledgeEntry = { ...INDEX_ARTIFACT, id: "zzz-copy" };
  const aaa: KnowledgeEntry = { ...INDEX_ARTIFACT, id: "aaa-copy" };
  const hits = findNearDuplicates(asCandidate(INDEX_ARTIFACT), [zzz, aaa]);
  expect(hits.map((h) => h.id)).toEqual(["aaa-copy", "zzz-copy"]);
  expect(hits[0]!.score).toBe(hits[1]!.score);
});
