// Entry lifecycle (plan 013 WP1): the six optional frontmatter fields, the extended
// round-trip guard, parse-time validation (allowlist + pairing + enums/dates), the
// active-only INDEX, and the cross-entry integrity checks. The load-bearing property
// is byte-identity: a field-less entry and an all-active INDEX must serialize EXACTLY
// as before (the corpus + INDEX.md are byte-match gated).

import { test, expect } from "bun:test";
import {
  parseEntry,
  serializeEntry,
  renderIndex,
  isActive,
  checkLifecycle,
} from "../src/index";
import { roundTrips } from "../src/file-store";
import type { KnowledgeEntry } from "../src/index";

const base: KnowledgeEntry = {
  id: "sample-lesson",
  type: "lesson",
  title: "A sample lesson",
  tags: ["a", "b"],
  source: "plan-008",
  created: "2026-06-26",
  body: "Body line one.\n",
};

// An entry with EVERY new lifecycle field populated (superseded ⇒ supersededBy).
const full: KnowledgeEntry = {
  id: "full-entry",
  type: "pattern",
  title: "A fully-populated entry",
  tags: ["x", "y"],
  source: "plan-013",
  created: "2026-06-26",
  status: "superseded",
  supersededBy: "newer-entry",
  updated: "2026-07-01",
  verifiedAt: "2026-07-02",
  origin: "reflection",
  links: ["storage-is-a-port", "components-at-root"],
  body: "The body.\n",
};

// --- Golden byte-identity ---

test("an entry WITHOUT lifecycle fields serializes byte-identically to the pre-lifecycle format", () => {
  const expected =
    "---\n" +
    "id: sample-lesson\n" +
    "type: lesson\n" +
    "title: A sample lesson\n" +
    "tags: [a, b]\n" +
    "source: plan-008\n" +
    "created: 2026-06-26\n" +
    "---\n" +
    "\n" +
    "Body line one.\n";
  expect(serializeEntry(base)).toBe(expected);
  // No lifecycle key leaks in when the fields are absent.
  for (const key of ["status:", "supersededBy:", "updated:", "verifiedAt:", "origin:", "links:"]) {
    expect(serializeEntry(base)).not.toContain(key);
  }
});

test("renderIndex over an all-active corpus emits the exact pre-lifecycle header (no '(archived)')", () => {
  const out = renderIndex([base, { ...base, id: "b-entry", title: "B" }]);
  expect(out).toContain(
    "> Generated by `bun run kb:index` — do NOT hand-edit. 2 entries.\n",
  );
  expect(out).not.toContain("archived");
});

// --- Round-trip with every new field ---

test("serialize -> parse round-trips an entry with EVERY lifecycle field populated", () => {
  expect(parseEntry(full.id, serializeEntry(full))).toEqual(full);
});

test("lifecycle fields serialize in the specified order after `created`", () => {
  const text = serializeEntry(full);
  const order = [
    "created:",
    "status:",
    "supersededBy:",
    "updated:",
    "verifiedAt:",
    "origin:",
    "links:",
  ].map((k) => text.indexOf(k));
  for (let i = 1; i < order.length; i++) {
    expect(order[i]).toBeGreaterThan(order[i - 1]!);
  }
  expect(text).toContain("links: [storage-is-a-port, components-at-root]");
});

test("parse tolerates CRLF on an entry carrying lifecycle fields", () => {
  const crlf = serializeEntry(full).replace(/\n/g, "\r\n");
  expect(parseEntry(full.id, crlf)).toEqual(full);
});

// --- Per-field guard naming: mutate a serialized field's value so it drifts, the
// round-trip guard must NAME that field (a forgotten comparison = silent lossy write). ---

test("the round-trip guard names each lifecycle field when the serialized value drifts", () => {
  // status: a trailing space trims back to a valid enum but ≠ the entry's value.
  expect(roundTrips({ ...full, status: "superseded " as never }, serializeEntry(full))).toBe(
    "field `status`",
  );
  // supersededBy
  expect(
    roundTrips(
      { ...full, supersededBy: "other-id" },
      serializeEntry({ ...full, supersededBy: "newer-entry" }),
    ),
  ).toBe("field `supersededBy`");
  // updated
  expect(
    roundTrips({ ...full, updated: "2026-01-01" }, serializeEntry({ ...full, updated: "2026-07-01" })),
  ).toBe("field `updated`");
  // verifiedAt
  expect(
    roundTrips(
      { ...full, verifiedAt: "2026-01-01" },
      serializeEntry({ ...full, verifiedAt: "2026-07-02" }),
    ),
  ).toBe("field `verifiedAt`");
  // origin
  expect(
    roundTrips({ ...full, origin: "manual" }, serializeEntry({ ...full, origin: "reflection" })),
  ).toBe("field `origin`");
  // links
  expect(
    roundTrips(
      { ...full, links: ["storage-is-a-port"] },
      serializeEntry({ ...full, links: ["storage-is-a-port", "components-at-root"] }),
    ),
  ).toBe("field `links`");
});

// --- Parse validation ---

test("parseEntry rejects an unknown frontmatter key (typo hazard, not silently ignored)", () => {
  const bad =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nstatu: superseded\n---\nbody\n";
  expect(() => parseEntry("x", bad)).toThrow(/unknown frontmatter key "statu"/);
});

test("parseEntry enforces the status:superseded <-> supersededBy pairing (both directions)", () => {
  const supNoTarget =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nstatus: superseded\n---\nbody\n";
  expect(() => parseEntry("x", supNoTarget)).toThrow(/status "superseded" requires supersededBy/);
  const targetNoSup =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nsupersededBy: other-id\n---\nbody\n";
  expect(() => parseEntry("x", targetNoSup)).toThrow(/supersededBy requires status "superseded"/);
});

test("parseEntry rejects a bad status, origin, or date", () => {
  const badStatus =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nstatus: retired\n---\nbody\n";
  expect(() => parseEntry("x", badStatus)).toThrow(/invalid status/);
  const badOrigin =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\norigin: robot\n---\nbody\n";
  expect(() => parseEntry("x", badOrigin)).toThrow(/invalid origin/);
  const badDate =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nupdated: 2026-7-1\n---\nbody\n";
  expect(() => parseEntry("x", badDate)).toThrow(/invalid updated/);
  const badVerified =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nverifiedAt: yesterday\n---\nbody\n";
  expect(() => parseEntry("x", badVerified)).toThrow(/invalid verifiedAt/);
});

test("parseEntry rejects a non-kebab link id", () => {
  const badLink =
    "---\nid: x\ntype: lesson\ntitle: t\ncreated: 2026-06-26\nlinks: [Not_Kebab]\n---\nbody\n";
  expect(() => parseEntry("x", badLink)).toThrow(/link "Not_Kebab" must be kebab-case/);
});

// --- checkLifecycle: cross-entry integrity ---

test("checkLifecycle flags a dangling supersededBy target", () => {
  const a: KnowledgeEntry = {
    ...base,
    id: "a",
    status: "superseded",
    supersededBy: "ghost",
  };
  const errs = checkLifecycle([a]);
  expect(errs.some((e) => /superseded by missing entry "ghost"/.test(e))).toBe(true);
});

test("checkLifecycle flags a self-link and a link to a missing entry", () => {
  const a: KnowledgeEntry = { ...base, id: "a", links: ["a", "nope"] };
  const errs = checkLifecycle([a]);
  expect(errs.some((e) => /"a" links to itself/.test(e))).toBe(true);
  expect(errs.some((e) => /links to missing entry "nope"/.test(e))).toBe(true);
});

test("checkLifecycle detects a self-cycle and a 2-cycle over supersededBy", () => {
  // Self-cycle (a -> a). parseEntry allows supersededBy===id; the graph check catches it.
  const selfCycle: KnowledgeEntry = {
    ...base,
    id: "a",
    status: "superseded",
    supersededBy: "a",
  };
  expect(checkLifecycle([selfCycle]).some((e) => /cycle detected/.test(e))).toBe(true);

  // 2-cycle (a -> b -> a).
  const a: KnowledgeEntry = { ...base, id: "a", status: "superseded", supersededBy: "b" };
  const b: KnowledgeEntry = { ...base, id: "b", status: "superseded", supersededBy: "a" };
  expect(checkLifecycle([a, b]).some((e) => /cycle detected/.test(e))).toBe(true);
});

test("checkLifecycle passes a clean supersession chain", () => {
  const a: KnowledgeEntry = { ...base, id: "a", status: "superseded", supersededBy: "b" };
  const b: KnowledgeEntry = { ...base, id: "b", links: ["a"] };
  expect(checkLifecycle([a, b])).toEqual([]);
});

// --- Active-only INDEX ---

test("isActive: absent status and 'active' are active; superseded/deprecated are not", () => {
  expect(isActive(base)).toBe(true);
  expect(isActive({ ...base, status: "active" })).toBe(true);
  expect(isActive({ ...base, status: "superseded", supersededBy: "x" })).toBe(false);
  expect(isActive({ ...base, status: "deprecated" })).toBe(false);
});

test("renderIndex drops superseded/deprecated entries and shows '(N archived)' only when N>0", () => {
  const active: KnowledgeEntry = { ...base, id: "active-one", title: "Active One" };
  const superseded: KnowledgeEntry = {
    ...base,
    id: "old-one",
    title: "Old One",
    status: "superseded",
    supersededBy: "active-one",
  };
  const deprecated: KnowledgeEntry = {
    ...base,
    id: "dead-one",
    title: "Dead One",
    status: "deprecated",
  };
  const out = renderIndex([active, superseded, deprecated]);
  expect(out).toContain("1 entries (2 archived).");
  expect(out).toContain("Active One");
  expect(out).not.toContain("Old One");
  expect(out).not.toContain("Dead One");

  // All active → no suffix.
  expect(renderIndex([active])).toContain(
    "> Generated by `bun run kb:index` — do NOT hand-edit. 1 entries.\n",
  );
});
