// `bun run kb:curate` — the lifecycle edge over FileKnowledgeStore (plan 013 WP1).
// One mode per invocation; each mode is a thin CLI over an update()/supersede() call,
// then INDEX.md is regenerated by the store. This is the human/loop-facing curation
// path that keeps the loaded index bounded (supersede/deprecate archive; verify ages).
//
//   bun run kb:curate --supersede <old-id> --json '<KnowledgeEntryInput>'
//   bun run kb:curate --deprecate <id> [--reason "<text>"]
//   bun run kb:curate --verify <id> [<id>...]
//   bun run kb:curate --update <id> --json '<KnowledgeEntryPatch>'

import { join } from "node:path";
import { readFileSync } from "node:fs";
import { FileKnowledgeStore } from "@objectcore/knowledge";
import type { KnowledgeEntryInput, KnowledgeEntryPatch } from "@objectcore/knowledge";

const args = process.argv.slice(2);

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function fail(msg: string): never {
  console.error(`✗ kb:curate failed: ${msg}`);
  process.exit(1);
}

function usage(): never {
  console.error(
    [
      "usage (one mode per invocation):",
      "  bun run kb:curate --supersede <old-id> --json '<KnowledgeEntryInput>'   (or --json @file.json)",
      '  bun run kb:curate --deprecate <id> [--reason "<text>"]',
      "  bun run kb:curate --verify <id> [<id>...]",
      "  bun run kb:curate --update <id> --json '<KnowledgeEntryPatch>'          (or --json @file.json)",
    ].join("\n"),
  );
  process.exit(2);
}

/** The value immediately after `flag`, or undefined; rejects a following flag. */
function flagArg(flag: string): string | undefined {
  const i = args.indexOf(flag);
  if (i === -1) return undefined;
  const v = args[i + 1];
  return v && !v.startsWith("--") ? v : undefined;
}

/** Parse `--json '<...>'` (inline) or `--json @file.json` — mirrors kb-add.ts. */
function readJson(): unknown {
  const i = args.indexOf("--json");
  if (i === -1 || !args[i + 1]) fail("this mode needs --json '<...>' (or --json @file.json)");
  const raw = args[i + 1]!;
  const json = raw.startsWith("@") ? readFileSync(raw.slice(1), "utf8") : raw;
  try {
    return JSON.parse(json);
  } catch (e) {
    return fail(`--json is not valid JSON: ${(e as Error).message}`);
  }
}

const MODES = ["--supersede", "--deprecate", "--verify", "--update"] as const;
const present = MODES.filter((m) => args.includes(m));
if (present.length !== 1) usage();
const mode = present[0];

const root = join(import.meta.dir, "..");
const store = new FileKnowledgeStore(join(root, "knowledge"));

try {
  if (mode === "--supersede") {
    const oldId = flagArg("--supersede");
    if (!oldId) fail("--supersede needs an <old-id>");
    const input = readJson() as KnowledgeEntryInput;
    const { superseded, replacement } = await store.supersede(oldId, input);
    console.log(
      `✓ superseded "${superseded.id}" → "${replacement.id}"; INDEX.md regenerated.`,
    );
  } else if (mode === "--deprecate") {
    const id = flagArg("--deprecate");
    if (!id) fail("--deprecate needs an <id>");
    const reason = flagArg("--reason");
    const existing = await store.get(id);
    if (!existing) fail(`entry "${id}" does not exist`);
    const patch: KnowledgeEntryPatch = { status: "deprecated" };
    if (reason) {
      patch.body = `${existing.body.trimEnd()}\n\n> Deprecated (${today()}): ${reason}`;
    }
    const updated = await store.update(id, patch);
    console.log(`✓ deprecated "${updated.id}"; INDEX.md regenerated.`);
  } else if (mode === "--verify") {
    const i = args.indexOf("--verify");
    const ids = args.slice(i + 1).filter((a) => !a.startsWith("--"));
    if (!ids.length) fail("--verify needs at least one <id>");
    const stamp = today();
    for (const id of ids) {
      const updated = await store.update(id, { verifiedAt: stamp });
      console.log(`✓ verified "${updated.id}" (verifiedAt: ${stamp})`);
    }
    console.log("✓ INDEX.md regenerated.");
  } else {
    // --update
    const id = flagArg("--update");
    if (!id) fail("--update needs an <id>");
    const patch = readJson() as KnowledgeEntryPatch;
    const updated = await store.update(id, patch);
    console.log(`✓ updated "${updated.id}"; INDEX.md regenerated.`);
  }
} catch (e) {
  // The store rejects frontmatter-breaking / inconsistent edits BEFORE writing —
  // surface the reason so the caller (human or the reflection loop) can fix it.
  fail((e as Error).message);
}
