// The bounded index — the KB's equivalent of the derived marketplace.json. Pure:
// entries in, index text out. INDEX.md is a BUILD ARTIFACT (never hand-edited);
// `kb:check` asserts the committed file byte-matches this output, the same
// never-hand-edit + byte-match discipline as the catalog.

import type { KnowledgeEntry } from "./types";
import { ENTRY_TYPES } from "./types";

/** The loaded-at-startup budget from Claude Code's memory pattern
 *  (code.claude.com/docs/en/memory): first 200 lines / 25KB. Overflow is the
 *  signal to curate/prune — the rot mechanism the index split alone doesn't give. */
export const INDEX_MAX_LINES = 200;
export const INDEX_MAX_BYTES = 25 * 1024;

/** An entry reaches the loaded index only while ACTIVE — status absent or "active".
 *  `superseded`/`deprecated` entries are archived (bounded forgetting): they stay on
 *  disk (diffable history) but drop out of the budget-checked index. */
export function isActive(e: KnowledgeEntry): boolean {
  return e.status === undefined || e.status === "active";
}

/** Render the bounded index from entries. Deterministic: grouped by type, sorted
 *  by id within each group, so the output is stable for byte-match checks. Only
 *  ACTIVE entries are rendered (archived ones reclaim budget by construction). */
export function renderIndex(entries: KnowledgeEntry[]): string {
  const active = entries.filter(isActive);
  const archived = entries.length - active.length;
  // Byte-identical to the pre-lifecycle format when nothing is archived; the
  // "(N archived)" suffix appears ONLY when N > 0.
  const count =
    archived > 0
      ? `${active.length} entries (${archived} archived).`
      : `${active.length} entries.`;
  const out: string[] = [
    "# ObjectCore Knowledge Base — Index",
    "",
    `> Generated by \`bun run kb:index\` — do NOT hand-edit. ${count}`,
    "> The factory's growing memory: lessons, patterns, gotchas, and decisions the",
    "> build + eval loop reads on the way in and writes on the way out. Bounded to",
    `> ${INDEX_MAX_LINES} lines / ${INDEX_MAX_BYTES / 1024}KB (the loaded-at-startup budget); when it`,
    "> overflows, curate or prune — that overflow is the rot signal.",
    "",
  ];
  for (const type of ENTRY_TYPES) {
    const group = active
      .filter((e) => e.type === type)
      .sort((a, b) => a.id.localeCompare(b.id));
    if (!group.length) continue;
    out.push(`## ${type}`);
    for (const e of group) {
      const tags = e.tags.length ? ` — _${e.tags.join(", ")}_` : "";
      // Escape link-text delimiters so a bracketed title still renders a valid link.
      out.push(`- [${e.title.replace(/([\[\]])/g, "\\$1")}](entries/${e.id}.md)${tags}`);
    }
    out.push("");
  }
  return out.join("\n").trimEnd() + "\n";
}

export interface BudgetCheck {
  ok: boolean;
  lines: number;
  bytes: number;
}

/** Is the rendered index within the loaded-at-startup budget? */
export function checkIndexBudget(indexText: string): BudgetCheck {
  const lines = indexText.split("\n").length;
  const bytes = new TextEncoder().encode(indexText).length;
  return { ok: lines <= INDEX_MAX_LINES && bytes <= INDEX_MAX_BYTES, lines, bytes };
}
